import type { FormKey } from '@/types'
import { useId } from 'vue'

export const useFormKey = (key?: FormKey) => {
  const warningRaised = useState('use-form-key/warning-raised', () => false)
  const trimmedKey = key?.trim() ?? ''
  const warningNotYetRaisedOnClient = import.meta.client && !warningRaised.value

  if (!trimmedKey && warningNotYetRaisedOnClient) {
    console.warn(
      'Tip: Add a unique key to every useForm configuration to improve debugging.',
    )
    warningRaised.value = true
  }

  const autoGeneratedKey = useId()
  const formKey = trimmedKey || autoGeneratedKey

  return formKey
}
